name: EcoTrack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}  # Inject the JWT_SECRET into the environment

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm run install:all

    - name: Run Prettier
      run: npm run prettier:all

    - name: Run ESLint
      run: npm run lint:all
    
    - name: Run server tests
      run: npm run test:server
        