name: EcoTrack CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: npm run install-all
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run server tests
      run: npm run test:server
        